title: Karl L. Hughes
description: > # this means to ignore newlines until "baseurl:"
  Technology team builder and startup enthusiast. Currently CTO at The Graide Network and Founder at Portable CTO.
permalink: 'posts/:title'
baseurl: "/personal-blog-5"
url: "https://karllhughes.github.io/"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Karl L. Hughes # add your name
author-img: karl.jpg # add your photo
about-author: Technology team builder and startup enthusiast.
social-twitter: karllhughes # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: karllhughes # add your Github handle
social-linkedin: karllhughes # add your Linkedin handle
social-email: khughes.me@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-19700764-2 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "legacy-data"]
