title: Karl Hughes
description: > # this means to ignore newlines until "baseurl:"
  Buying and Scaling Digital Service Businesses
permalink: 'posts/:title'
baseurl: ""
url: "https://www.karllhughes.com"

# Author Settings
author: Karl Hughes # add your name
author-img: karl.png # add your photo
social-twitter: karllhughes # add your Twitter handle
# social-facebook: # add your Facebook handle
# social-github: karllhughes # add your Github handle
social-linkedin: karllhughes # add your Linkedin handle
social-tiktok: founderdaily # add your tiktok handle
social-email: khughes.me@gmail.com # add your Email address
social-rss: /feed

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-19700764-2 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "legacy-data", ".idea"]
